### ISSUE TITLE
Вопросики

### ISSUE THREAD

**Issue by lex10000** [dadowl/uptimer#1]
Проблемки
1)Не пингует по ip (по домену пингует). Ubuntu 18 версия (если запускать через sudo - то работает).

Общие рекомендации
1) Разделить конфиг на несколько файлов (конфиг для подключения каналов связи (телеграм, почта, etc), конфиг серверов для пинга, общие настройки).
2) Проверить, что если что-то удалено из конфига, то либо вывести ошибку, либо использовать дефолные хардкодовые значения.
3) Валидация json конфига - выкинуть человеческую ошибку в случае провала

**Comment by dadowl** [comment]
Я там сделал про что вы говорили. 
Разделил конфиги, добавил валидацию в json.
Новая версия 2.0.0
